# Минимальный конфиг для сборки клиента под macOS и публикации в GitHub Release.
# Без Docker, Homebrew, подписи и прочих издателей.
version: 2

project_name: netbird

builds:
  - id: netbird
    dir: client
    binary: netbird
    env: [CGO_ENABLED=0]
    goos: [darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - load_wgnt_from_rsrc

archives:
  - id: default
    builds: [netbird]
    format: tar.gz

release:
  name_template: "{{ .Version }}"
  draft: false
